#!/usr/bin/env python
"""
Django's Command-Line Utility

PURPOSE:
Entry point for all Django management commands.
This file is auto-generated by django-admin startproject.

USAGE:
    python manage.py <command> [options]

COMMON COMMANDS:
    python manage.py runserver          # Start development server
    python manage.py migrate            # Apply database migrations
    python manage.py makemigrations     # Create new migrations from model changes
    python manage.py createsuperuser    # Create an admin user
    python manage.py shell              # Open Django Python shell
    python manage.py check              # Check for common problems
    
CUSTOM COMMANDS (defined in app/management/commands/):
    python manage.py list_events        # List Google Calendar events

HOW IT WORKS:
1. Sets DJANGO_SETTINGS_MODULE environment variable to point to settings.py
2. Imports Django's command-line execution machinery
3. Runs the command you specified
"""
import os
import sys


def main():
    """
    Main entry point for Django management commands.
    
    WHAT THIS DOES:
    1. Set default settings module (config.settings)
    2. Import Django's execute_from_command_line function
    3. Pass command-line arguments to Django
    
    The actual command logic is in Django's core or in
    app/management/commands/ for custom commands.
    """
    # Tell Django which settings file to use
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
    
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    
    # Run the command
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()
