# Generated by Django 6.1.1 on 2026-09-07 22:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('calendar_id', models.CharField(help_text="Calendar ID (usually 'primary')", max_length=255, primary_key=True, serialize=False)),
                ('sync_token', models.CharField(blank=True, default='', help_text="Google's syncToken for incremental sync", max_length=1024)),
                ('last_full_sync', models.DateTimeField(blank=True, help_text='When we last did a complete sync', null=True)),
                ('last_sync', models.DateTimeField(auto_now=True, help_text='When we last synced (any type)')),
            ],
        ),
        migrations.CreateModel(
            name='WatchChannel',
            fields=[
                ('channel_id', models.UUIDField(default=uuid.uuid4, help_text='Our UUID for this watch channel', primary_key=True, serialize=False)),
                ('resource_id', models.CharField(blank=True, default='', help_text="Google's resource ID for this channel", max_length=255)),
                ('calendar_id', models.CharField(db_index=True, help_text='Calendar ID being watched', max_length=255)),
                ('webhook_url', models.URLField(help_text='Webhook URL for notifications')),
                ('token', models.CharField(help_text='Secret token to verify notifications', max_length=256)),
                ('expiration', models.DateTimeField(help_text='When this channel expires')),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Whether this channel is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When we created this channel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('google_event_id', models.CharField(help_text="Google's unique event identifier", max_length=1024, primary_key=True, serialize=False)),
                ('calendar_id', models.CharField(db_index=True, help_text="Calendar ID (usually 'primary')", max_length=255)),
                ('summary', models.CharField(blank=True, default='', help_text='Event title/summary', max_length=1024)),
                ('start_time', models.DateTimeField(db_index=True, help_text='Event start time (UTC)')),
                ('end_time', models.DateTimeField(help_text='Event end time (UTC)')),
                ('all_day', models.BooleanField(default=False, help_text='True if this is an all-day event')),
                ('duration_minutes', models.IntegerField(default=0, help_text='Duration in minutes (computed from start/end)')),
                ('attendee_count', models.IntegerField(default=0, help_text='Number of attendees')),
                ('organizer_email', models.CharField(blank=True, default='', help_text="Organizer's email address", max_length=255)),
                ('status', models.CharField(db_index=True, default='confirmed', help_text='Event status (confirmed/tentative/cancelled)', max_length=50)),
                ('raw_json', models.JSONField(default=dict, help_text='Full event data from Google API')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When we first synced this event')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When we last updated this event')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['calendar_id', 'start_time'], name='calsync_cal_calenda_1a706a_idx'), models.Index(fields=['calendar_id', 'status'], name='calsync_cal_calenda_a800cb_idx')],
            },
        ),
    ]
