# Generated by Django 6.1.1 on 2026-09-10 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calsync', '0002_multi_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text="Attendee's email address", max_length=255)),
                ('display_name', models.CharField(blank=True, default='', help_text="Attendee's display name from Google", max_length=255)),
                ('response_status', models.CharField(blank=True, default='', help_text='RSVP status (accepted / declined / tentative / needsAction)', max_length=50)),
                ('is_self', models.BooleanField(default=False, help_text='True when this attendee is the calendar owner')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='calendarevent',
            name='calsync_calendarevent_user_event_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='syncstate',
            name='calsync_syncstate_user_cal_uniq',
        ),
        migrations.RenameIndex(
            model_name='calendarevent',
            new_name='calsync_cal_user_id_2d35b4_idx',
            old_name='calsync_calendarevent_user_cal_start_idx',
        ),
        migrations.RenameIndex(
            model_name='calendarevent',
            new_name='calsync_cal_user_id_4799e2_idx',
            old_name='calsync_calendarevent_user_cal_status_idx',
        ),
        migrations.AlterUniqueTogether(
            name='calendarevent',
            unique_together={('user', 'google_event_id')},
        ),
        migrations.AlterUniqueTogether(
            name='syncstate',
            unique_together={('user', 'calendar_id')},
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='event',
            field=models.ForeignKey(help_text='Event this attendee belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='calsync.calendarevent'),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='user',
            field=models.ForeignKey(help_text='Owner of the calendar (denormalized for query performance)', on_delete=django.db.models.deletion.CASCADE, related_name='event_attendees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='eventattendee',
            index=models.Index(fields=['user', 'email'], name='calsync_eve_user_id_c1b2f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventattendee',
            unique_together={('event', 'email')},
        ),
    ]
